# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainApp(object):
    def setupUi(self, MainApp):
        MainApp.setObjectName("MainApp")
        MainApp.resize(450, 470)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainApp.sizePolicy().hasHeightForWidth())
        MainApp.setSizePolicy(sizePolicy)
        MainApp.setStyleSheet("*\n"
"{\n"
"font: 9pt \"MS Reference Sans Serif\";\n"
"}\n"
"\n"
"\n"
"QLabel#fondo\n"
"{\n"
"    background-image: url(:/neuron_music/img/fondo_login.png);\n"
"\n"
"\n"
"}\n"
"QLabel#logo_neuron\n"
"{\n"
"\n"
"background-image: url(:/neuron_music/img/logo_neuron.png);\n"
"border-image: url(:/neuron_music/img/logo_neuron.png);\n"
"\n"
"}\n"
"#boton_aceptar\n"
"{\n"
"\n"
"border-radius: 10px;\n"
"background-color: rgb(21, 210, 169);\n"
"font:bold;\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"#boton_aceptar:hover\n"
"{\n"
"    background-color: rgba(139, 255, 201, 237);\n"
"\n"
"}\n"
"#boton_aceptar:hover:pressed\n"
"{\n"
" background-color: rgba(139, 139, 139, 233);\n"
"color:  rgb(21, 210, 169);\n"
"}\n"
"#l_inicio\n"
"{\n"
"background-color: rgb(21, 210, 169);\n"
"border-radius: 10px;\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"#label_email\n"
"{\n"
"background-image: url(:/neuron_music/img/line_email.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"#label_pass\n"
"{\n"
"background-image: url(:/neuron_music/img/line_password.png);\n"
"background-repeat: no-repeat;\n"
"}\n"
"#fondo_email, #fondo_pass\n"
"{\n"
"background-color: rgb(191, 191, 191);\n"
"border-radius: 10px;\n"
"}\n"
" QLineEdit\n"
"{\n"
"border-radius: 10px;\n"
"\n"
"}\n"
"QLabel#rectangulo\n"
"{\n"
"border-width: 3px;\n"
"border-style: solid;\n"
" border-radius: 15px;\n"
"border-color:  #FFFFFF;\n"
"\n"
"\n"
"}\n"
"#fondo_email:hover, #fondo_pass:hover\n"
"{\n"
"background-color: rgba(139, 139, 139, 233);\n"
"\n"
"}\n"
"QLabel#rectangulo:hover\n"
"{\n"
"border-color:rgba(139, 139, 139, 233);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.principal = QtWidgets.QWidget(MainApp)
        self.principal.setObjectName("principal")
        self.boton_aceptar = QtWidgets.QPushButton(self.principal)
        self.boton_aceptar.setGeometry(QtCore.QRect(220, 360, 121, 31))
        self.boton_aceptar.setObjectName("boton_aceptar")
        self.user = QtWidgets.QLineEdit(self.principal)
        self.user.setGeometry(QtCore.QRect(170, 220, 171, 41))
        self.user.setClearButtonEnabled(True)
        self.user.setObjectName("user")
        self.password = QtWidgets.QLineEdit(self.principal)
        self.password.setGeometry(QtCore.QRect(170, 290, 171, 41))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.logo_neuron = QtWidgets.QLabel(self.principal)
        self.logo_neuron.setGeometry(QtCore.QRect(-10, -10, 181, 141))
        self.logo_neuron.setText("")
        self.logo_neuron.setObjectName("logo_neuron")
        self.l_inicio = QtWidgets.QLabel(self.principal)
        self.l_inicio.setGeometry(QtCore.QRect(110, 110, 251, 91))
        self.l_inicio.setAlignment(QtCore.Qt.AlignCenter)
        self.l_inicio.setObjectName("l_inicio")
        self.label_email = QtWidgets.QLabel(self.principal)
        self.label_email.setGeometry(QtCore.QRect(140, 230, 31, 31))
        self.label_email.setText("")
        self.label_email.setObjectName("label_email")
        self.label_pass = QtWidgets.QLabel(self.principal)
        self.label_pass.setGeometry(QtCore.QRect(140, 300, 31, 31))
        self.label_pass.setText("")
        self.label_pass.setObjectName("label_pass")
        self.fondo = QtWidgets.QLabel(self.principal)
        self.fondo.setGeometry(QtCore.QRect(-20, -30, 481, 511))
        self.fondo.setObjectName("fondo")
        self.fondo_email = QtWidgets.QLabel(self.principal)
        self.fondo_email.setGeometry(QtCore.QRect(130, 220, 71, 41))
        self.fondo_email.setText("")
        self.fondo_email.setObjectName("fondo_email")
        self.fondo_pass = QtWidgets.QLabel(self.principal)
        self.fondo_pass.setGeometry(QtCore.QRect(130, 290, 71, 41))
        self.fondo_pass.setText("")
        self.fondo_pass.setObjectName("fondo_pass")
        self.rectangulo = QtWidgets.QLabel(self.principal)
        self.rectangulo.setGeometry(QtCore.QRect(120, 100, 251, 91))
        self.rectangulo.setText("")
        self.rectangulo.setObjectName("rectangulo")
        self.acento = QtWidgets.QLabel(self.principal)
        self.acento.setGeometry(QtCore.QRect(299, 137, 31, 21))
        self.acento.setObjectName("acento")
        self.fondo.raise_()
        self.boton_aceptar.raise_()
        self.logo_neuron.raise_()
        self.l_inicio.raise_()
        self.fondo_email.raise_()
        self.user.raise_()
        self.label_email.raise_()
        self.fondo_pass.raise_()
        self.password.raise_()
        self.label_pass.raise_()
        self.rectangulo.raise_()
        self.acento.raise_()
        MainApp.setCentralWidget(self.principal)

        self.retranslateUi(MainApp)
        QtCore.QMetaObject.connectSlotsByName(MainApp)

    def retranslateUi(self, MainApp):
        _translate = QtCore.QCoreApplication.translate
        MainApp.setWindowTitle(_translate("MainApp", "Neuron Music"))
        self.boton_aceptar.setText(_translate("MainApp", "Aceptar"))
        self.user.setPlaceholderText(_translate("MainApp", "correo electrónico"))
        self.password.setPlaceholderText(_translate("MainApp", "contraseña"))
        self.l_inicio.setText(_translate("MainApp", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Inicio de Ses</span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">io</span><span style=\" font-size:14pt; font-weight:600;\">n</span></p></body></html>"))
        self.fondo.setText(_translate("MainApp", "º"))
        self.acento.setText(_translate("MainApp", "<html><head/><body><p><span style=\" font-size:22pt; color:#ffffff;\">´</span></p></body></html>"))
